centerThonPre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls")),
    path('community/', include("community.urls")),
    path('mypage/', include("mypage.urls")),
    path('', include('product.urls', namespace='product')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# media 경로 추가

community/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path('', views.community_view, name="community"),
    path("buy_review", views.buy_review, name="review"),
    path("free_board", views.freeboard_view, name="freeboard"),
    path('<int:pk>/', views.freeboard_list, name="freeboardDetail"),
    path('post/', views.freeboard_post, name="freeboardPost"),
    path('<int:pk>/edit/', views.freeboard_edit, name="freeboardEdit"),
]

order/urls.py
from django.urls import path
from . import views
from .views import create_order
app_name = 'order'

urlpatterns = [
    path('product/order/', create_order, name='order_create'),

    ]

community/models.py
from django.db import models
from users.models import User

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

community/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

community/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
# from django.contrib.auth import authenticate, login, logout
# from django.shortcuts import redirect
# from .models import User
from .models import Post
from .forms import PostForm
# Create your views here.

def buy_review(request):
    return render(request, "community/review.html")

def freeboard_view(request):
    posts = Post.objects.all()
    return render(request, "community/freeboard.html", {'posts': posts})

def community_view(request):
    return render(request, "community/community.html")

def freeboard_list(request, pk):
    post = Post.objects.get(id=pk)
    return render(request, 'community/freeboardDetail.html', {'post': post})

@login_required
def freeboard_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            # return redirect('community:freeboard')
            return render(request, 'community/freeboardDetail.html', {'post': post})
    else:
        form = PostForm()
    return render(request, 'community/freeboardPost.html', {'form': form})

@login_required
def freeboard_edit(request, pk):
    post = Post.objects.get(id=pk)

    # 권한 검사
    if post.author != request.user:
        return HttpResponseForbidden("You don't have permission to edit this post.")

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return render(request, 'community/freeboardDetail.html', {'post': post})
    else:
        form = PostForm(instance=post)
    return render(request, 'community/freeboardPost.html', {'form': form})

community/templates/community/community.html
커뮤니티 앱의 메인 페이지
<br>
<br>
<a href="{% url 'community:review' %}">구매후기</a>
<br>
<a href="{% url 'community:freeboard' %}">자유게시판</a>

community/templates/community/freeboard.html
<html>
    <head>
        <title>자유게시판 앱</title>
        <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    </head>
    <body>
    <div class="container">
        <h1>게시판 글 목록</h1>
        <p>
        <a href="{% url 'community:community' %}" class="btn btn-primary">커뮤니티 홈으로</a>
        </p>
        <p>
        <a href="{% url 'community:freeboardPost' %}" class="btn btn-primary">게시판 글쓰기</a>
        </p>
        <ul class="list-group">
        {% for post in posts %}
        <li class="list-group-item">
            <a href="{% url 'community:freeboardDetail' pk=post.pk %}">{{ post.title }}</a>
        </li>
        {% endfor %}
        </ul>
    </body>
    </div>
</html>

community/templates/community/freeboardDetail.html
<html>
    <head>
        <title>freeboard 목록 앱</title>
        <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    </head>
    <body>
    <div class="container">
        <h1>freeboard 상세보기</h1>

        <div class="container">
        <div class="row">
            <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                     <a href="{% url 'community:freeboardEdit' pk=post.pk %}" class="btn btn-outline-primary"> 수정하기</a>
                <h5 class="card-title">{{ post.title }}</h5>
                </h5>
                <p class="card-text">{{ post.content }}</p>
                    <p class="card-text">{{ post.created_at }}</p>
                    <p class="card-text">{{ post.author }}</p>
                <a href="{% url 'community:freeboard' %}" class="btn btn-primary">목록으로</a>
                </div>
            </div>
            </div>
        </div>
        </div>
    </body>
    </div>
</html>

community/templates/community/freeboardPost.html
<html>
    <head>
        <title>freeBoard</title>
        <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    </head>
    <body>
    <div class="container">
        <h1>freeBoard 추가하기</h1>
        <div class="container">
        <div class="row">
            <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                <form method="POST">
                    {% csrf_token %} {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">등록</button>
                </form>
                </div>
            </div>
            </div>
        </div>
        </div>
    </body>
    </div>
</html>

community/templates/community/review.html
구매 리뷰 페이지