centerThonPre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls")),
    path('community/', include("community.urls")),
    path('mypage/', include("mypage.urls")),
    path('', include('product.urls', namespace='product')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# media 경로 추가

order/urls.py
from django.urls import path
from . import views
from .views import create_order
app_name = 'order'

urlpatterns = [
    path('product/order/', create_order, name='order_create'),

    ]

product/urls.py
from django.urls import path
from . import views
from .views import product_delete, edit_product, product_create,product_list,product_detail
app_name = 'product'
urlpatterns = [
    path('product/create/', product_create, name='product_post'),
    path('product/', product_list, name='product_list'),
    path('product/<int:pk>/', product_detail, name='product_detail'),
    path('product/<int:pk>/delete/', product_delete, name='product_delete'),
    path('product/order/', views.order_list, name='order_list'),
    path('product/order/<int:pk>/', views.order_done, name='order_done'),
    path('product/<int:pk>/edit/', edit_product, name='product_edit'),
    ]

product/models.py
from django.db import models
from users.models import User

class Product(models.Model):
    DISTRICT_CHOICES = (
        ('강남구', '강남구'),
        ('강동구', '강동구'),
        ('강북구', '강북구'),
        ('강서구', '강서구'),
        ('관악구', '관악구'),
        ('광진구', '광진구'),
        ('구로구', '구로구'),
        ('금천구', '금천구'),
        ('노원구', '노원구'),
        ('도봉구', '도봉구'),
        ('동대문구', '동대문구'),
        ('동작구', '동작구'),
        ('마포구', '마포구'),
        ('서대문구', '서대문구'),
        ('서초구', '서초구'),
        ('성동구', '성동구'),
        ('성북구', '성북구'),
        ('송파구', '송파구'),
        ('양천구', '양천구'),
        ('영등포구', '영등포구'),
        ('용산구', '용산구'),
        ('은평구', '은평구'),
        ('종로구', '종로구'),
        ('중구', '중구'),
        ('중랑구', '중랑구'),
    )
    address = models.CharField(max_length=50, choices=DISTRICT_CHOICES,null=True)
    detail_address = models.CharField(max_length=50,null=True)
    product_name = models.CharField(max_length=256, verbose_name='상품명')
    price = models.IntegerField(verbose_name='상품가격')
    description = models.TextField(verbose_name='상품 상세설명')
    product_image = models.FileField(upload_to='images/', verbose_name='상품 이미지', null=True, default=None)
    add_date = models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')
    order_status = models.BooleanField(default=False, verbose_name='주문상태') #주문상태
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name='구매자')
    def __str__(self):
        return self.product_name

    class Meta:
        db_table = 'my_product'
        verbose_name = '상품'
        verbose_name_plural = '상품'
# Create your models here.

product/forms.py
from django import forms
from .models import Product
from django.contrib.auth import get_user

class RegisterForm(forms.Form):
    product_name = forms.CharField(max_length=64, label='상품명')
    price = forms.IntegerField(label='상품가격')
    description = forms.CharField(label='상품설명')
    product_image = forms.FileField(label='상품이미지')
    address = forms.ChoiceField(label='구', choices=Product.DISTRICT_CHOICES)
    detail_address = forms.CharField(label='상세주소')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({'class': 'form-select'})
    def save(self, request):
        product_name = self.cleaned_data['product_name']
        price = self.cleaned_data['price']
        description = self.cleaned_data['description']
        product_image = request.FILES['product_image']  # 이미지 파일 가져오기
        author = request.user
        address = self.cleaned_data['address']

        product = Product(
            product_name=product_name,
            price=price,
            description=description,
            author=author,
            address=address,
        )
        product.product_image.save(product_image.name, product_image)  # 이미지 파일 저장
        product.save()


class EditForm(forms.ModelForm):
    product_name = forms.CharField(max_length=64, label='상품명')
    price = forms.IntegerField(label='상품가격')
    description = forms.CharField(label='상품설명')
    product_image = forms.FileField(label='상품이미지')
    class Meta:
        model = Product
        fields = ('product_name','price','description','product_image')

product/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView
from .models import Product
from .forms import RegisterForm, EditForm
from django.contrib.auth import get_user


# Create your views here.
def product_list(request):
    '''product_list = Product.objects.all()
    return render(request, 'product/product.html', {'product_list': product_list})'''
    address_filter = request.GET.get('address', '')  # 주소 필터링 값을 가져옴

    if address_filter:  # 주소 필터링 값이 있다면 해당 주소의 게시글만 필터링
        product_list = Product.objects.filter(address=address_filter)
    else:  # 주소 필터링 값이 없다면 모든 게시글 표시
        product_list = Product.objects.filter()

    address_choices = Product.DISTRICT_CHOICES  # 주소 선택지

    context = {
        'product_list':  product_list,
        'address_choices': address_choices,
        'selected_address': address_filter,  # 선택한 주소를 템플릿으로 전달
    }
    return render(request, 'product/product.html', context)


def product_create(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)  # 파일을 처리하기 위해 request.FILES 전달

        if form.is_valid():
            form.save(request=request)
            return redirect('/product/')
    else:
        form = RegisterForm()
    return render(request, 'product/register_product.html', {'form': form})


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'product/product_detail.html', {'product': product})

def product_delete(request, pk):
    product = Product.objects.get(id=pk)
    product.delete()
    return redirect('product_list')

def order_list(request): #책이랑 다르게 작성함
    dones = Product.objects.filter(order_status=True)
    return render(request, 'product/order_list.html', {'dones': dones})

def order_done(request, pk):
    product = Product.objects.get(id=pk)
    product.order_status = True
    product.customer = request.user
    product.save()
    return redirect('product:product_list')

def edit_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        form = EditForm(request.POST, request.FILES, instance=product)
        if form.is_valid():

            form.save()
            return redirect('/product/')
    else:
        form = EditForm(instance=product)

    return render(request, 'product/edit_product.html', {'form': form})

product/templates/product/edit_product.html
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/summernote/0.8.12/summernote-bs4.js"></script> -->
<script>
    $(document).ready(function () {
        $('#id_description').summernote({
            height: 300
        });
    });
</script>

<div class="row mt-5">
    <div class="col-12 text-center">
        <h1>상품 수정하기</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="POST" action="." enctype="multipart/form-data">
             {% csrf_token %} {{ form.as_p }}


            <button type="submit" class="btn btn-primary">수정</button>
        </form>
    </div>
</div>

product/templates/product/order_list.html
<html>
<head>
    <title>주문 목록</title>
    <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>
<body>
    <div class="container">
        <h1>주문 완료 목록</h1>
        <p>
            <a href="{% url 'product:product_list' %}" class="btn btn-primary">홈으로</a>
        </p>
        <ul class="list-group">
            {%for done in dones%}
            <li class="list-group-item">
                <a href="{% url 'product:product_detail' pk=done.pk %}">{{done.product_name}}</a>

            </li>
            {%endfor%}
        </ul>
    </div>
</body>
</html>

product/templates/product/product.html
<div class="row mt-5">
    <div class="col-12">
        <table class="table table-light">
            <thead class="thead-light">
            {{ user.username }}
            <br>
             <form method="GET" action="{% url 'product:product_list' %}">
            <div class="form-group">
                <label for="address">주소:</label>
               <select name="address" class="form-control" id="address">
                {% for value, display_text in address_choices %}
                <option value="{{ value }}" {% if value == selected_address %}selected{% endif %}>{{ display_text }}</option>
                 {% endfor %}
            </select>
            </div>
            <button type="submit" class="btn btn-primary">필터 적용</button>
            </form>
                <tr>
                    <th space="col">상품명(클릭하면 상세내역 이동)</th>
                    <th space="col">가격</th>
                    <th space="col">등록날짜</th>
                    <th space="col">이미지</th>
                     <th space="col">게시자</th>
                    <th space="col">구매자</th>
                </tr>
            </thead>
            <tbody class="text-dark">
                {% for product in product_list|dictsortreversed:"add_date" %}
                {% if product.order_status == False %}
                <tr>

                    <th><a href="/product/{{ product.id }}">{{ product.product_name }}</a></th>
                    <th>{{ product.price}} 원</th>
                    <th>{{ product.add_date |date:'Y-m-d H:i' }}</th>
                     <th><img src="{{ product.product_image.url }}" alt="Product Image"></th>
                     <th>{{ product.author }}</th>
                     <th>{{ product.customer }}</th>
                </tr>
                {% endif %}
                {% endfor %}
                <a href="{% url 'product:product_post' %}" class="btn btn-outline-primary">상품 생성하기</a></p>
             <a href="{% url 'product:order_list' %}" class="btn btn-outline-primary">주문목록 보러가기</a></p>
            </tbody>
        </table>
    </div>
</div>

product/templates/product/product_detail.html
<div class="row mt-5">
    <div class="col-12">
        <div class="card" style="width: 100%;">
            {{ user.username }}
            <div class="card-body">
                <h5 class="card-title">{{ product.product_name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">가격: {{ product.price }} 원</li>
                <li class="list-group-item">등록날짜: {{ product.add_date |date:'Y-m-d H:i' }}</li>
                <li class="list-group-item">{{ product.description|safe }}</li>
                <th>주문 상태 : {{ product.order_status}} </th>
                {% if product.product_image %}
                    <img src="{{ product.product_image.url }}" alt="Product Image">
                {% endif %}
                <a href="{% url 'product:product_delete' product.pk %}" class="btn btn-outline-primary">삭제</a></p>
                <a href="{% url 'product:order_done' product.pk  %}" class="btn btn-outline-primary">주문</a></p>
                <a href="{% url 'product:product_edit' product.pk  %}" class="btn btn-outline-primary">수정</a></p>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <a href="/product/">목록보기</a>
    </div>
</div>

product/templates/product/register_product.html
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/summernote/0.8.12/summernote-bs4.js"></script> -->
<script>
    $(document).ready(function () {
        $('#id_description').summernote({
            height: 300
        });
    });
</script>

<div class="row mt-5">
    <div class="col-12 text-center">
        <h1>상품 생성하기</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
             <p class="p2">{{ form.product_name.label_tag }} {{ form.product_name }}</p>
            <p class="p2">{{ form.price.label_tag }} {{ form.price }}</p>
            <p class="p2">{{ form.description.label_tag }} {{ form.description }}</p>
            <p class="p2">{{ form.product_image.label_tag }} {{ form.product_image }}</p>
            <p class="p2">{{ form.address.label_tag }} {{ form.address }}</p>
            <p class="p2">{{ form.detail_address.label_tag }} {{ form.detail_address }}</p>
            <button type="submit" class="btn btn-primary">생성</button>
        </form>
    </div>
</div>