centerThonPre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls")),
    path('community/', include("community.urls")),
    path('mypage/', include("mypage.urls")),
    path('', include('product.urls', namespace='product')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# media 경로 추가

mypage/urls.py
from django.urls import path
from . import views

app_name = "mypage"

urlpatterns = [
    path('', views.mypage_view, name="mypage"),
    path("edit", views.edit_view, name="edit"),
    path('profile/update/', views.profile_update_view, name='profile_update'),

]

order/urls.py
from django.urls import path
from . import views
from .views import create_order
app_name = 'order'

urlpatterns = [
    path('product/order/', create_order, name='order_create'),

    ]

product/urls.py
from django.urls import path
from . import views
from .views import product_delete, edit_product, product_create,product_list,product_detail
app_name = 'product'
urlpatterns = [
    path('product/create/', product_create, name='product_post'),
    path('product/', product_list, name='product_list'),
    path('product/<int:pk>/', product_detail, name='product_detail'),
    path('product/<int:pk>/delete/', product_delete, name='product_delete'),
    path('product/order/', views.order_list, name='order_list'),
    path('product/order/<int:pk>/', views.order_done, name='order_done'),
    path('product/<int:pk>/edit/', edit_product, name='product_edit'),
    ]

mypage/models.py
from django.db import models
from users.models import User

# Create your models here.

mypage/forms.py
from django.contrib.auth.forms import UserChangeForm
from users.models import User

class CustomCsUserChangeForm(UserChangeForm):
    class Meta:
        model = User()
        fields = ['username', 'email']

mypage/views.py
from django.shortcuts import render
from django.contrib import messages

from product.models import Product
from .forms import CustomCsUserChangeForm



def mypage_view(request):

    posts = Product.objects.filter(author=request.user)
    buys = Product.objects.filter(customer=request.user)
    context = {
        'posts': posts,
        'buys': buys
    }
    return render(request, "mypage/mypage.html", context)

def edit_view(request):
    return render(request, "mypage/info_edit.html")

def profile_update_view(request):
    if request.method == 'POST':
        user_change_form = CustomCsUserChangeForm(request.POST, instance = request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, "mypage/mypage.html")
        else:
            print(user_change_form.errors)
            # return render(request, "mypage/mypage.html")
    else:
        user_change_form = CustomCsUserChangeForm(instance = request.user)

        return render(request, 'mypage/info_edit.html', {'user_change_form':user_change_form})

mypage/templates/mypage/info_edit.html
{% block mobileView %}
<meta name="viewport" content="width=550, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div style="margin-top: 5rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-edit"></i>&nbsp;&nbsp;내 정보수정</strong>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <table style="color:black; margin-left:10px;">
                                <tr>
                                    <td class="profile_title">아이디</td>
                                    <td class="profile_content">&nbsp;&nbsp;{{ user_change_form.username }}&nbsp;&nbsp;님</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">이메일</td>
                                    <td class="profile_content">&nbsp;&nbsp;{{ user_change_form.email }}</td>
                                </tr>
                            </table>
                            <div style="text-align: center; margin-bottom:-15px;">
                                <a onclick="location.href='/mypage'" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;돌아가기</a>
                                <button type="submit" class="btn btn-sm" id="detail_btn"><i class="fas fa-check"></i>&nbsp;수정하기</button>
                            </div>
                        </form>
                        
                        <script type = "text/javascript">
                            function maxLengthCheck(object){
                                if (object.value.length > object.maxLength) {
                                    object.value = object.value.slice(0, object.maxLength);
                                    }   
                                }
                        </script>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mypage/templates/mypage/mypage.html
마이페이지
<br>
<br>
<table>
    <tr>
        <td>아이디</td>
        <td>{{ user.username }}님</td>
    </tr>
<table>
    <tr>
        <td>상품 게시 목록</td>
    </tr>
    <tr>
        <td>
            {% for product in posts %}
               <a href="{% url 'product:product_detail' product.pk %}">{{ product.product_name }}</a><br>
            {% endfor %}
        </td>
    </tr>
    <tr>
        <td>상품 구매 목록</td>
    </tr>
    <tr>
        <td>
            {% for product in buys %}
                <a href="{% url 'product:product_detail' product.pk %}">{{ product.product_name }}</a><br>
            {% endfor %}
        </td>
    </tr>
</table><br>
<!--<a href="{% url 'mypage:edit' %}"> 정보 수정</a>-->
<a href="{% url 'mypage:profile_update' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;내정보수정</a>&nbsp;