centerThonPre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls")),
    path('community/', include("community.urls")),
    path('mypage/', include("mypage.urls")),
    path('', include('product.urls', namespace='product')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# media 경로 추가

order/urls.py
from django.urls import path
from . import views
from .views import create_order
app_name = 'order'

urlpatterns = [
    path('product/order/', create_order, name='order_create'),

    ]

users/urls.py
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup")
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField()
# Create your models here.

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .models import User
# Create your views here.

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password = password)
        if user is not None:
            print("인증성공")
            login(request,user)
        else:
            print("인증실패")
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        email = request.POST["email"]

        # 사용자 이름(username)이 이미 존재하는지 확인
        if User.objects.filter(username=username).exists():
            return render(request, "users/signup.html", {"error": "이미 사용 중인 사용자 이름입니다."})

        user = User.objects.create_user(username, email, password)
    #     user.last_name = lastname
        user.save()
        return redirect("user:login")

    return render(request, "users/signup.html")

users/templates/users/login.html
로그인페이지
<br>
{% if user.is_authenticated %}
    로그인성공!
    {{ user.username }}님 환영합니다.
    <a href="{% url 'user:logout' %}">로그아웃</a>
{% else %}

<form action="" method="POST">
    {% csrf_token %}
    <input name="username" type="text">
    <input name="password" type="password">
    <input type="submit" value="로그인">
</form>
<a href="{% url 'user:signup' %}">회원가입</a>

{% endif %}

users/templates/users/signup.html
회원가입 페이지
<br>

<form action="" method="POST">
    {% csrf_token %}
    <p>아이디</p>
    <input name="username" type="text">
    <p>비밀번호</p>
    <input name="password" type="password">
    <p>이메일</p>
    <input name="email" type="text">
    <input type="submit" value="회원가입">
    {% if error %}
    <p>{{ error }}</p>
    {% endif %}
</form>